#!/usr/bin/php
<?php
/**
 * starter script for the Dime console application
 */

require __DIR__.'/vendor/autoload.php';

use DimeConsole\ActivitiesCommand;
use DimeConsole\DimeShellApplication;

$application = new DimeShellApplication();
$application->add(new ActivitiesCommand());
$application->run();